---
- name: Remove old monitoring-lite resources
  ansible.builtin.shell: |
    microk8s kubectl delete namespace monitoring-lite --ignore-not-found
  when: "'masters' in group_names"
  run_once: true


- name: Add Prometheus community Helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"
    binary_path: /usr/local/bin/helm
  when: "'masters' in group_names"

- name: Install full Kube-Prometheus-Stack
  kubernetes.core.helm:
    name: prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    binary_path: /usr/local/bin/helm
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    values:
      grafana:
        service:
          type: NodePort
          nodePort: 32300
      prometheus:
        prometheusSpec:
          retention: 10d
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: manual
                resources:
                  requests:
                    storage: 10Gi
  when: "'masters' in group_names"
