apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredesk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredesk-app
  template:
    metadata:
      labels:
        app: coredesk-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: oss02
      containers:
        - name: coredesk-app
          image: jackcranee/sluopenproject-oss:0.0.1
          env:
            # S3 Configuration from our new Secret
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: coredesk-env-secrets
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: coredesk-env-secrets
                  key: AWS_REGION
            - name: AWS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: coredesk-env-secrets
                  key: AWS_ENDPOINT
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: coredesk-env-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: coredesk-env-secrets
                  key: AWS_SECRET_ACCESS_KEY
            
            # Database URI from the CloudNativePG Operator Secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: coredesk-db-app
                  key: uri
            
            # JWT and Env settings
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: coredesk-env-secrets
                  key: JWT_SECRET
            - name: NODE_ENV
              value: "production"
            - name: PROJECT_NAME
              value: "CoreDesk"
---
apiVersion: v1
kind: Service
metadata:
  name: coredesk-service
spec:
  type: NodePort
  selector:
    app: coredesk-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
      nodePort: 30080
