apiVersion: v1
kind: Secret
metadata:
  name: coredesk-env-secrets
  namespace: default
type: Opaque
stringData:
  AWS_BUCKET: "BUCKET"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT: "https://s3.amazonaws.com"
  AWS_ACCESS_KEY_ID: "key-id"
  AWS_SECRET_ACCESS_KEY: "secret"
  JWT_SECRET: "fake"
