apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coredesk-db
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: manual
    pvcTemplate:
      # No 'spec:' here!
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      selector:
        matchLabels:
          usage: coredesk-db
  bootstrap:
    initdb:
      database: coredesk
      owner: postgres
