apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:        # ADD THIS
    usage: coredesk-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  claimRef:
    name: coredesk-db-1
    namespace: default
  local:
    path: /mnt/data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - oss02
