---
- name: Ensure the infrastructure user exists
  user:
    name: sluinfra
    shell: /bin/bash
    groups: sudo
    append: yes
 

- name: Create lab data directory
  file:
    path: /mnt/lab_data
    state: directory
    owner: sluinfra
    mode: '0755'
 

- name: Ensure native curl is installed (fixes Snap sandbox errors)
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: yes
  become: yes

- name: Install Python3-pip and system dependencies
  ansible.builtin.apt:
    name: 
      - python3-pip
      - python3-setuptools
    state: present
  become: yes

- name: Install Kubernetes and Helm libraries via Pip
  ansible.builtin.pip:
    name: 
      - kubernetes
      - PyYAML
    state: present
  become: yes

- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'
  become: yes

- name: Run Helm install script
  ansible.builtin.shell: /tmp/get_helm.sh
  become: yes
  args:
    creates: /usr/local/bin/helm

- name: Optimize system limits
  pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: nofile
    value: 65535
