
# Phase 1: Prepare the machine you are typing on
- name: Local Environment Prep
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure K8s collection is installed locally
      ansible.builtin.command: ansible-galaxy collection install kubernetes.core
      changed_when: false

# Phase 2: Deploy to the SLU Cluster
- name: Deploy Open Source SLU Infrastructure
  hosts: all
  become: yes
  roles:
    - { role: system_base, tags: ['base'] }
    - { role: node_provision, tags: ['provision'] } # Now handles Pip/K8s libs
    - { role: k8s_prep, tags: ['k8s_prep'] }
    - { role: monitoring, tags: ['monitoring'] }
    - { role: argocd, tags: ['cicd'] }
    - { role: database_operator, tags: ['db'] }
    - { role: app_deploy, tags: ['app_deploy'] }
